# General settings
name: 'graph-tf-model'                   # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'                # online | offline | disabled
gpus: 1                     # Multi-gpu is currently not implemented

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 5
sample_every_val: 2
val_check_interval: null
samples_to_generate: 1024
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

faster_sampling: 1                              # At each sampling step, set s=t-faster sampling (1 for normal sampling)

final_model_samples_to_generate: 10000
final_model_samples_to_save: 10
final_model_chains_to_save: 5

cpus_per_gpu: 4
force_ray: false

evaluate_all_checkpoints: False
num_final_sampling: 5