# Training settings
n_epochs: 1000

batch_size: 256
reference_batch_size: 300
lr: 0.0002
clip_grad: null          # float, null to disable
save_model: True
num_workers: 0
ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
progress_bar: false
weight_decay: 1e-12
scheduler: null #
seed: 0